:reproducible:

= Capability Manipulation Instructions

{proj_name} provides instructions for creating, modifying, and destroying capabilities.
Note that due to the guarantee of provenance of capabilities, those instructions are
the _only_ way to manipulate capabilities. In particular, it is not possible to manipulate
capabilities by manipulating the content of a memory location or register using
other instructions.

== Cursor, Bounds, and Permissions Manipulation

[#cap-mov]
=== Capability Movement

Capabilities can be moved between registers with the MOVC instruction.

.MOVC instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001010' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability
****

*If no exception is raised:*

====
* If `rs1 = rd`, the instruction is a no-op.
* Otherwise
. Write `x[rs1]` to `x[rd]`
. If `x[rs1]` is not a non-linear capability (i.e., `type != 1`),
write `cnull` to `x[rs1]`.
====

[#cursor-inc]
=== Cursor Increment

The CINCOFFSET and CINCOFFSETIMM instructions increment the `cursor` of a
capability by a given amount (offset).

==== CINCOFFSET

.CINCOFFSET instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0001100' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Unexpected capability type (26)`
- `x[rs1]` has `type = 3` (uninitialised) or `type = 4` (sealed).
****

*If no exception is raised:*

====
. Set `val` to `x[rs2]`.
. `MOVC rd, rs1`.
. Set `x[rd].cursor` to `x[rd].cursor + val`.
====

==== CINCOFFSETIMM

.CINCOFFSETIMM instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b010' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Unexpected capability type (26)`
- `x[rs1]` has `type = 3` (uninitialised) or `type = 4` (sealed).
****

*If no exception is raised:*

====
. `MOVC rd, rs1`.
. Set `x[rd].cursor` to `x[rd].cursor + imm`.
====

[#cursor-set]
=== Cursor Setter

The `cursor` field of a capability can also be directly set with the SCC instruction.

.SCC instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0000101' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Unexpected capability type (26)`
- `x[rs1]` has `type = 3` (uninitialised) or `type = 4` (sealed).
****

*If no exception is raised:*

====
. Set `val` to `x[rs2]`.
. `MOVC rd, rs1`.
. Set `x[rd].cursor` to `val`.
====

[#field-query]
=== Field Query

The LCC instruction is used to read a field from a capability.

.LCC instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'imm[4:0] (Z)' },
    {bits: 7, name: '0b0000100' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Unexpected capability type (26)`
- `imm = 2` and `x[rs1]` has `type = 4` (sealed).
- `imm = 4` and `x[rs1]` has `type = 4` (sealed), `type = 5` (sealed-return), or `type = 6` (exit).
- `imm = 5` and `x[rs1]` has `type = 4` (sealed), `type = 5` (sealed-return), or `type = 6` (exit).
- `imm = 6` and `x[rs1]` does not have `type = 4` (sealed) or `type = 5` (sealed-return).
- `imm = 7` and `x[rs1]` does not have `type = 5` (sealed-return).
****

*If no exception is raised:*

====
* If `imm > 7`, write `zero` to `x[rd]`
* Otherwise, write `field` to `x[rd]`
according to the <<lcc-multiplex,LCC multiplexing table>>.
====

[#lcc-multiplex]
.LCC multiplexing table
[%header,%autowidth.stretch]
|===
|`imm` | `field`
|`0` | `x[rs1].valid`
|`1` | `x[rs1].type`
|`2` | `x[rs1].cursor`
|`3` | `x[rs1].base`
|`4` | `x[rs1].end`
|`5` | `x[rs1].perms`
|`6` | `x[rs1].async`
|`7` | `x[rs1].reg`
|===

[#shrink]
=== Bounds Shrinking

The bounds (`base` and `end` fields) of a capability can be shrunk with the SHRINK instruction.

.SHRINK instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0000001' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rd]` is not a capability.
- `x[rs1]` is not an integer.
- `x[rs2]` is not an integer.
* `Unexpected capability type (26)`
- `x[rd].type` is not `0`, `1`, or `3` (linear, non-linear, or uninitialised).
* `Illegal operand value (29)`
- `x[rs1] >= x[rs2]`.
- `x[rs1] < x[rd].base` or `x[rs2] > x[rd].end`.
****

*If no exception is raised:*

====
. Set `x[rd].base` to `x[rs1]` and `x[rd].end` to `x[rs2]`.
. If `x[rd].cursor < x[rs1]`, set `x[rd].cursor` to `x[rs1]`.
. If `x[rd].cursor > x[rs2]`, set `x[rd].cursor` to `x[rs2]`.
====

[#split]
=== Bounds Splitting

The SPLIT instruction can split a capability into two by splitting the bounds.
It attempts to split the capability `x[rs1]` into two capabilities,
one with bounds `[x[rs1].base, x[rs2])` and the other with bounds `[x[rs2], x[rs1].end)`.

.SPLIT instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0000110' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is neither `0` (linear) nor `1` (non-linear).
* `Illegal operand value (29)`
- `x[rs2] \<= x[rs1].base` or `x[rs2] >= x[rs1].end`.
****

*If no exception is raised:*

====
. If `rs1 = rd`, the instruction is a no-op.
// in case rs2 = rd
. Set `val` to `x[rs2]`.
. Write `x[rs1]` to `x[rd]`.
. Set `x[rs1].end` to `val`, `x[rs1].cursor` to `x[rs1].base`.
. Set `x[rd].base` to `val`, `x[rd].cursor` to `val`.
====

[#tighten]
=== Permission Tightening

The TIGHTEN instruction tightens the permissions (`perms` field) of a capability.

.TIGHTEN instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'imm[4:0] (Z)' },
    {bits: 7, name: '0b0000010' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0`, `1`, or `3` (linear, non-linear, or uninitialised).
* `Illegal operand value (29)`
- `imm \<= 7`, and `imm \<=p x[rs1].perms` does not hold.
****

*If no exception is raised:*

====
. `MOVC rd, rs1`.
. If `imm > 7`, set `x[rs1].perms` to `0`.
Otherwise, set `x[rs1].perms` to `imm`.
====

== Type Manipulation

Some instructions can affect the `type` field of a capability directly. 
In general, the `type` field cannot be set arbitrarily.
Instead, it is changed as the side effect of certain semantically significant operations.

[#delin]
=== Delinearisation

The DELIN instruction delinearises a linear capability.

.DELIN instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: '*' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0000011' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rd]` is not a capability.
* `Unexpected capability type (26)`
- `x[rd].type` is not `0` (linear).
****

*If no exception is raised:*

====
* Set `x[rd].type` to `1` (non-linear).
====

[#init]
=== Initialisation

The INIT instruction transforms an uninitialised capability into a linear capability
after its associated memory region has been fully initialised (written with new data).

.INIT instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0001001' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Unexpected capability type (26)`
- `x[rs1].type` is not `3` (uninitialised).
* `Illegal operand value (29)`
- `x[rs1].cursor` and `x[rs1].end` are not equal.
****

*If no exception is raised:* 

====
. Set `val` to `x[rs2]`.
. `MOVC rd, rs1`.
. Set `x[rd].type` to `0` (linear), and `x[rd].cursor` to `x[rd].base + val`.
====

[#seal]
=== Sealing

The SEAL instruction seals a linear capability.

.SEAL instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0000111' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear).
* `Insufficient capability permissions (27)`
- `6 \<=p x[rs1].perms` does not hold.
* `Illegal operand value (29)`
- The size of the memory region associated with `x[rs1]` is smaller than
`CLENBYTES * 33` bytes (i.e., `x[rs1].end - x[rs1].base < CLENBYTES * 33`).
- `x[rs1].base` is not aligned to `CLENBYTES` bytes.
****

*If no exception is raised:* 

====
. `MOVC rd, rs1`.
. Set `x[rd].type` to `2` (sealed), and `x[rd].async` to `0` (synchronous).
====

[#drop]
== Dropping

The DROP instruction invalidates a capability.

.DROP instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001011' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
****

*If no exception is raised:*

====
. If `x[rs1].valid` is `0` (invalid), the instruction is a no-op.
. Otherwise, set `x[rs1].valid` to `0` (invalid).
====

[#revocation]
== Revocation

[#revcap-creation]
=== Revocation Capability Creation

The MREV instruction creates a revocation capability.

.MREV instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001000' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear).
****

*If no exception is raised:*

====
. Write `x[rs1]` to `x[rd]`.
. Set `x[rd].type` to `2` (revocation).
====

[#rev-operation]
=== Revocation Operation

The REVOKE instruction revokes a capability.

.REVOKE instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0000000' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `2` (revocation).
****

*If no exception is raised:*

====
. For each capability `c` in the system (in either a register or
memory location), `c.valid` is set to `0` (invalid)
if any of the following conditions are met:

* `c.type` is not `2` (revocation), `c.valid` is `1` (valid),
and `c` <<alias-definition,aliases>> with `x[rs1]`.
* `c.type` is `2` (revocation), `c.valid` is `1` (valid), and `x[rs1] <<smaller-t-definition,<t>> c`.

. `x[rs1].type` is set to `0` (linear)
if at least one of the following conditions are met:

* For every invalidated capability `c`, the type of `c` is non-linear (i.e., `c.type` is `1`).
* `2 \<=p x[rs1].perms` does not hold.

. Otherwise, set `x[rs1].type` to `3` (uninitialised),
and `x[rs1].cursor` to `x[rs1].base`.
====
