:reproducible:

= Control Flow Instructions

[#jmp-cap]
== Jump to Capabilities

The CJALR and CBNZ instructions allow jumping to a capability,
i.e., setting the program counter to a given capability,
in a unconditional or conditional manner.

.CJALR instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100010' }
]}
....

.CBNZ instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100011' }
]}
....

*An exception is raised when any of the following conditions are met:*

* _{isa_var_pure}_
** `rs1` does not contain a capability.
** The `type` field of the capability in `rs1` is neither `0` (linear) nor `1` (non-linear).
** The `perms` field of the capability in `rs1` is neither `2` (read-execute) nor `4` (read-write-execute).
* _{isa_var_hybrid}_
** `cwrld` is `0` (normal world).
** Any of the conditions for _{isa_var_pure}_ are met.

*If no exception is raised:*

* CJAL: Set the program counter (`pc`) to the capability in `rs1`. Meanwhile, the existing
capability in `pc`, with its `cursor` field replaced by the address of the next instruction,
is written to the register `rd`.
* CBNZ: If the content of `rs2` is zero (`0`), the behaviour is the same as for NOP.
Otherwise, set the program counter (`pc`) to the capability in `rs1`.

[#domain-cross]
== Domain Crossing

_Domains_ in {isa_name} are individual software compartments that
are protected by a safe context switching mechanism, i.e., domain crossing.
The mechanism is provided by the CALL and RETURN instructions.

=== CALL

The CALL instruction is used to call a sealed capability, i.e., to switch to another _domain_.

.CALL instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100000' }
]}
....

*An exception is raised when any of the following conditions are met:*

* _{isa_var_pure}_
** `rs1` does not contain a capability.
** The `valid` field of the capability in `rs1` is `0` (invalid).
** The `type` field of the capability in `rs1` is not `4` (sealed).
** The `async` field of the capability in `rs1` is `1` (asynchronous).
* _{isa_var_hybrid}_
** `cwrld` is `0` (normal world).
** Any of the conditions for _{isa_var_pure}_ are met.

*If no exception is raised:*

. Load the content at the memory location `[rs1.base, rs1.base + CLENBYTES)` to the program counter (`pc`).
. Load the content at the memory location `[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` to the `ceh`.
. Load the content at the memory location `[rs1.base + 2 * CLENBYTES, rs1.base + 3 * CLENBYTES)` to the `csp`.
. Store the former `pc`, `ceh` and `csp` values to the memory location `[rs1.base, rs1.base + CLENBYTES)`,
`[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` and `[rs1.base + 2 * CLENBYTES, rs1.base + 3 * CLENBYTES)`
respectively.
. Set the `type` field of the capability in `rs1` to `5` (sealed-return), set the `reg` field of the
capability in `rs1` to `rd`, set th `async` field of the capability in `rs1` to `0` (synchronous),
and write the capability to the register `cra`.

=== RETURN

.RETURN instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100001' }
]}
....

*An exception is raised when any of the following conditions are met:*

* _{isa_var_pure}_
** `rs1` does not contain a capability.
** The `valid` field of the capability in `rs1` is `0` (invalid).
** The `type` field of the capability in `rs1` is not `5` (sealed-return).
** `rs2` does not contain an integer.
* _{isa_var_hybrid}_
** `cwrld` is `0` (normal world).
** Any of the conditions for _{isa_var_pure}_ are met.

*If no exception is raised:*

*When `rs1.async = 0` (synchronous):*

. Load the content at the memory location `[rs1.base, rs1.base + CLENBYTES)` to the program counter (`pc`).
. Load the content at the memory location `[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` to the `ceh`.
. Load the content at the memory location `[rs1.base + 2 * CLENBYTES, rs1.base + 3 * CLENBYTES)` to the `csp`.
. Store the former `pc`, `ceh` and `csp` values to the memory location `[rs1.base, rs1.base + CLENBYTES)`,
`[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` and `[rs1.base + 2 * CLENBYTES, rs1.base + 3 * CLENBYTES)`
respectively.
. Set the `type` field of the capability in `rs1` to `4` (sealed), and write the
capability to the register `x[reg]` where `reg` is the `reg` field of the capability in `rs1`.

*When `rs1.async = 1` (asynchronous):*

. Load the content at the memory location `[rs1.base, rs1.base + CLENBYTES)` to the program counter (`pc`).
. For `i = 1, 2, ..., 31`, load the content at the memory location
`[rs1.base + i * CLENBYTES, rs1.base + (i + 1) * CLENBYTES)`, to `x[i]` (the `i`-th general-purpose register).
. Write the former value of `pc`, with the `cursor` field replaced by the content of `rs2`, to
the memory location `[rs1.base, rs1.base + CLENBYTES)`.
. For `i = 1, 2, ..., 31`, store the content of `x[i]` (the `i`-th general-purpose register)
to the memory location `[rs1.base + i * CLENBYTES, rs1.base + (i + 1) * CLENBYTES)`.
When `i = rs1`, store the content of `cnull` instead to `[rs1.base + i * CLENBYTES, rs1.base + (i + 1) * CLENBYTES)`.
. Set the `type` field of the capability in `rs1` to `4` (sealed), and write the
capability to the exception handler register `ceh`.


.Note
****

When the `async` field of a sealed-return capability is `1` (asynchronous), some
memory accesses are granted by this capability. The following table shows the
memory accesses granted by sealed and sealed-return capabilities in different scenarios.

.Memory accesses granted by sealed and sealed-return capabilities
[%header%autowidth.stretch]
|===
| Capability type | `async` | Read | Write | Execute
| Sealed | `0` | No | No | No
| Sealed | `1` | No | No | No
| Sealed-return | `0` | No | No | No
| Sealed-return | `1` | `cursor in [base, end)` | `cursor in [base, end)` | No
|===

****

[#world-switch]
== A World Switching Extension for _{isa_var_hybrid}_

In _{isa_var_hybrid}_, a pair of extra instructions, i.e., CAPENTER and CAPEXIT,
is added to support switching between the secure world and the normal world. 
The CAPENTER instruction causes an entry into the secure world from the
normal world, and the CAPEXIT instruction causes an exit from the secure
world into the normal world.

The CAPENTER instruction can only be used in the normal world, whereas
the CAPEXIT instruction can only be used in the secure world.
In addition, the CAPEXIT instruction can only be used when an exit capability
is provided.
Attempting to use those instructions in the wrong world or without the
required capability will cause an exception.
The behaviours of these 2 instructions 
roughly correspond to the CALL and RETURN instructions respectively.

=== CAPENTER

.CAPENTER instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100100' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `1` (secure world).
* `rs1` does not contain a capability.
* The `valid` field of the capability in `rs1` is `0` (invalid).
* The `type` field of the capability in `rs1` is not `4` (sealed).

*If no exception is raised:*

// TODO: the resumption of an asynchronous exit needs to be handled

// TODO: we need to find a way to access the content in the switch_cap region

*When `rs1.async = 0` (synchronous):*

. Load the content at the memory location `[rs1.base, rs1.base + CLENBYTES)` to the program counter (`pc`).
. Load the content at the memory location `[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` to the `ceh`.
. Load the content at the memory location `[rs1.base + 2 * CLENBYTES, rs1.base + 3 * CLENBYTES)` to the `csp`.
. Store the former value of `pc` and `sp` to `normal_pc` and `normal_sp` respectively.
. Set the `type` field of the capability in `rs1` to `5` (sealed-return), set the `async` field of the
capability in `rs1` to `0` (synchronous), and write the capability to `switch_cap`.
. Write `rs1` to `switch_reg`.
. Create a capability of `type = 6` (exit) in `cra`.
. Set `exit_reg` to `rd`.
. Set `cwrld` to `1` (secure world).

*When `rs1.async = 1` (asynchronous):*

. Load the content at the memory location `[rs1.base, rs1.base + CLENBYTES)` to the program counter (`pc`).
. Load the content at the memory location `[rs1.base + CLENBYTES, rs1.base + 2 * CLENBYTES)` to the `ceh`.
. For `i = 1, 2, ..., 31`, load the content at the memory location
`[rs1.base + (i + 1) * CLENBYTES, rs1.base + (i + 2) * CLENBYTES)`, to `x[i]` (the `i`-th general-purpose register).
. Store the former value of `pc` and `sp` to `normal_pc` and `normal_sp` respectively.
. Set the `type` field of the capability in `rs1` to `5` (sealed-return), set the `async` field of the
capability in `rs1` to `0` (synchronous), and write the capability to `switch_cap`.
. Write `rs1` to `switch_reg`.
. Set `exit_reg` to `rd`.
. Set `cwrld` to `1` (secure world).

.Note
****

The `rd` register will be set to a value indicating the cause of exit when
the CPU core exits from the secure world synchronously or asynchronously.

****

=== CAPEXIT

.CAPEXIT instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100101' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `0` (normal world).
* `rs1` does not contain a capability.
* The `valid` field of the capability in `rs1` is `0` (invalid).
* The `type` field of the capability in `rs1` is not `6` (exit).
* `rs2` does not contain an integer.
* `switch_cap` does not contain a capability.
* The `valid` field of the capability in `switch_cap` is `0` (invalid).
* The `type` field of the capability in `switch_cap` is not `4` (sealed-return).
* The `async` field of the capability in `switch_cap` is `1` (asynchronous).

*If no exception is raised:*

. Write the content of `normal_pc` and `normal_sp` to `pc` and `sp` respectively.
. Write the former value of `pc`, with the `cursor` field replaced by the content of `rs2`,
to the memory location `[switch_cap.base, switch_cap.base + CLENBYTES)`.
. Write the former value of `ceh` and `csp` to the memory location
`[switch_cap.base + CLENBYTES, switch_cap.base + 2 * CLENBYTES)` and
`[switch_cap.base + 2 * CLENBYTES, switch_cap.base + 3 * CLENBYTES)` respectively.
. Set the `type` field of `switch_cap` to `4` (sealed), set the `async` field
of `switch_cap` to `0` (synchronous), and write it to `x[switch_reg]`.
. Set the register `x[exit_reg]` to `0` (normal exit).
. Set `cwrld` to `0` (normal world).
