:reproducible:

= Control Flow Instructions

== Jump to Capabilities

The CJALR and CBNZ instructions allow jumping to a capability,
i.e., setting the program counter to a given capability,
in a unconditional or conditional manner.

[#jmp-cap]
=== CJALR

.CJALR instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b101' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (2)`
- `cwrld` is `0` (normal world).
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
****

*If no exception is raised:*

====
. Set `cap` to `x[rs1]`.
. Set `pc.cursor` to `pc.cursor + 4`, write `pc` to `x[rd]`.
. Set `cap.cursor` to `cap.cursor + imm`, write `cap` to `pc`.
. If `rs1 != rd` and `x[rs1].type != 1`, write `cnull` to `x[rs1]`.
====

[#branch-cap]
=== CBNZ

.CBNZ instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b110' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (2)`
- `cwrld` is `0` (normal world).
* `Unexpected operand type (24)`
- `x[rd]` is not a capability.
- `x[rs1]` is not an integer.
****

*If no exception is raised:*

====
* If `x[rs1]` is `0`, the instruction is a no-op.
* Otherwise
. Write `x[rd]` to `pc`.
. Set `pc.cursor` to `pc.cursor + imm`.
. If `x[rd].type != 1`, write `cnull` to `x[rd]`.
====

[#domain-cross]
== Domain Crossing

_Domains_ in {isa_name} are individual software compartments that
are protected by a safe context switching mechanism, i.e., _domain crossing_.
The mechanism is provided by the CALL and RETURN instructions.

=== CALL

The CALL instruction is used to call a sealed capability, i.e., to switch to another _domain_.

.CALL instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100000' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (2)`
- `cwrld` is `0` (normal world).
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `4` (sealed).
- `x[rs1].async` is not `0` (synchronous).
****

*If no exception is raised:*

====
. `MOVC cra, rs1`.
. Swap the program counter (`pc`) with the content at the memory location `[cra.base, cra.base + CLENBYTES)`.
. Swap `ceh` with the content at the memory location `[cra.base + CLENBYTES, cra.base + 2 * CLENBYTES)`.
. Swap `csp` with the content at the memory location `[cra.base + 2 * CLENBYTES, cra.base + 3 * CLENBYTES)`.
. Set `cra.type` to `5` (sealed-return), `cra.cursor` to `cra.base`, `cra.reg` to `rd`,
and `cra.async` to `0` (synchronous).
====

=== RETURN

.RETURN instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100001' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (2)`
- `cwrld` is `0` (normal world).
* `Unexpected operand type (24)`
- `rs1 != 0` and `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Invalid capability (25)`
- `rs1 != 0` and `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `rs1 != 0` and `x[rs1].type` is not `5` (sealed-return).
- `rs1 != 0` and `x[rs1].async` is neither `0` (synchronous) nor `1` (upon exception).
****

*If no exception is raised:*

*If `rs1 = 0`:*

====
. Set `pc.cursor` to `x[rs2]`.
. Write `pc` to `ceh`, and `epc` to `pc`.
. If `epc.type != 1`, write `cnull` to `epc`.
====

*Otherwise:*

*When `x[rs1].async = 0` (synchronous):*

====
. Write `x[rs1]` to `cap` and `cnull` to `x[rs1]`.
// Use swap here in case rs2 is the register sp
. Set `pc.cursor` to `x[rs2]`, and swap the program counter (`pc`) with
the content at the memory location `[cap.base, cap.base + CLENBYTES)`.
. Swap `ceh` with the content at the memory location `[cap.base + CLENBYTES, cap.base + 2 * CLENBYTES)`.
. Swap `csp` with the content at the memory location `[cap.base + 2 * CLENBYTES, cap.base + 3 * CLENBYTES)`.
. Write `cap` to `x[cap.reg]` and set `x[cap.reg].type` to `4` (sealed).
====

*When `x[rs1].async = 1` (upon exception):*

====
. Set `pc.cursor` to `x[rs2]`, and swap the program counter (`pc`) with
the content at the memory location `[x[rs1].base, x[rs1].base + CLENBYTES)`.
// ceh is going to be overwritten, no need for a swap
. Store `ceh` to the memory location `[x[rs1].base + CLENBYTES, x[rs1].base + 2 * CLENBYTES)`.
. Set `x[rs1].type` to `4` (sealed), `x[rs1].async` to `0` (synchronous).
. Write the resulting `x[rs1]` to `ceh`, and `cnull` to `x[rs1]`.
. For `i = 1, 2, ..., 31`, swap `x[i]` with the content at the memory location
`[ceh.base + (i + 1) * CLENBYTES, ceh.base + (i + 2) * CLENBYTES)`.
====

== World Switching

The world switching mechanism of {isa_name} is provided by the CAPENTER and CAPEXIT instructions.

.Overview of world switching in {isa_name}
image::trans-sync.svg[trans-sync]

[#world-enter]
=== CAPENTER

The CAPENTER instruction causes an entry into the secure world from the normal world.
And it is only available in the normal world.

.CAPENTER instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100010' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (0)`
- `cwrld` is `1` (secure world).
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `4` (sealed).
****

*If no exception is raised:*

*When `x[rs1].async = 0` (synchronous):*

====
. `MOVC cra, rs1`.
. Write `pc` and `sp` to `normal_pc` and `normal_sp` respectively.
. Load the program counter (`pc`) from the memory location `[cra.base, cra.base + CLENBYTES)`.
. Load `ceh` from the memory location `[cra.base + CLENBYTES, cra.base + 2 * CLENBYTES)`.
. Load `csp` from the memory location `[cra.base + 2 * CLENBYTES, cra.base + 3 * CLENBYTES)`.
. Set `cra.type` to `6` (exit), `cra.cursor` to `cra.base`.
. Write `rs1` to `switch_reg`, `rd` to `exit_reg`.
. Set `cwrld` to `1` (secure world).
====

*When `x[rs1].async` is `1` (upon exception) or `2` (upon interrupt):*

====
. Write `x[rs1]` to `switch_cap`, and `cnull` to `x[rs1]`.
. Write `pc` and `sp` to `normal_pc` and `normal_sp` respectively.
. Load the program counter (`pc`) from the memory location `[switch_cap.base, switch_cap.base + CLENBYTES)`.
. Load `ceh` from the memory location `[switch_cap.base + CLENBYTES, switch_cap.base + 2 * CLENBYTES)`.
. For `i = 1, 2, ..., 31`, load `x[i]` from the memory location
`[switch_cap.base + (i + 1) * CLENBYTES, switch_cap.base + (i + 2) * CLENBYTES)`.
. Set `switch_cap.type` to `3` (uninitialised), `switch_cap.cursor` to `switch_cap.base`.
. Write `rs1` to `switch_reg`, `rd` to `exit_reg`.
. Set `cwrld` to `1` (secure world).
====

.*Note: the purpose of the `rd` operand*
[%collapsible]
====
****
The `rd` register will be set to a value indicating the cause of exit when
the CPU core exits from the secure world synchronously or asynchronously.
****
====

[#world-exit]
=== CAPEXIT

The CAPEXIT instruction causes an exit from the secure world into the normal world.
It is only available in the secure world and can only be used with an exit capability.

.CAPEXIT instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100011' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Illegal instruction (2)`
- `cwrld` is `0` (normal world).
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `6` (exit).
****

*If no exception is raised:*

====
. Write `x[rs1]` to `cap`, and `cnull` to `x[rs1]`.
. Set `pc.cursor` to `x[rs2]`, and write `pc`, `ceh`, and `csp`
to the memory location `[cap.base, cap.base + CLENBYTES)`,
`[cap.base + CLENBYTES, cap.base + 2 * CLENBYTES)`, and
`[cap.base + 2 * CLENBYTES, cap.base + 3 * CLENBYTES)` respectively.
. Write `normal_pc + 4` and `normal_sp` to `pc` and `sp` respectively.
. Set `cap.type` to `4` (sealed), `cap.async`
to `0` (synchronous), and write the resulting `cap` to `x[switch_reg]`.
. Set `x[exit_reg]` to `0` (normal exit).
. Set `cwrld` to `0` (normal world).
====
