:reproducible:

= Control Flow Instructions

[#jmp-cap]
== Jump to Capabilities

The JMP and JNZ instructions allow jumping to a capability, i.e.,
setting the program counter to a given capability.

.JMP instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100010' }
]}
....

.JNZ instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100011' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `rs1` does not contain a capability

*If no exception is raised:*
For JMP instruction, the program counter (`pc`)
is set to the capability in `rs1`. If the capability is valid and executable,
the next instruction will be fetched from its `cursor` field.

The behaviour of JNZ depends on the content of `rs2`:

* If the content of `rs2` is zero (`0`), the behaviour is the same as for NOP.
* Otherwise, the behaviour is the same as for JMP.

[#domain-cross]
== Domain Crossing

[#world-switch]
== World Switching
