:reproducible:

= Control State Instructions

[#ccsr-man]
== Capability CSR (CCSR) Manipulation

The CCSRRW instruction is used to read and write specified link:#ccsrs-list[capability CSRs] (CCSRs).

.CCSRRW instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (Z)' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `imm` (i.e., the zero-extension of the immediate value `imm[11:0]`) does not correspond to
any encoding of a valid CCSR.
* `rs1` does not contain a capability.

*If no exception is raised:*

. Read from CCSR
** If the link:#ccsr-man-constr[read constraint] is satisfied: the content of the CCSR specified
by `imm` (i.e., the zero-extension of the immediate value `imm[11:0]`) is written to the register `rd`.
If the content of the CCSR is not a non-linear capability (i.e., `type != 1`), it will be set to the content of `cnull`.
** Otherwise, the content of the register `rd` is set to the content of `cnull`.
. Write to CCSR
** If the link:#ccsr-man-constr[write constraint] is satisfied, the content of the register `rs1` 
is written to the CCSR specified by `imm` (i.e., the zero-extension of the immediate value `imm[11:0]`).
If the content of the register `rs1` is not a non-linear capability (i.e., `type != 1`), it will be set to the content of `cnull`.
** Otherwise (i.e., the write constraint is broke), the current content of the CCSR is preserved.
