:reproducible:

= Control Flow Instructions

[#jmp-cap]
== Jump to Capabilities

The JMP and JNZ instructions allow jumping to a capability, i.e.,
setting the program counter to a given capability.

.JMP instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100010' }
]}
....

.JNZ instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100011' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `0` (normal world).
* `rs1` does not contain a capability.

*If no exception is raised:*
For JMP instruction, the program counter (`pc`)
is set to the capability in `rs1`. If the capability is valid and executable,
the next instruction will be fetched from its `cursor` field.

The behaviour of JNZ depends on the content of `rs2`:

* If the content of `rs2` is zero (`0`), the behaviour is the same as for NOP.
* Otherwise, the behaviour is the same as for JMP.

[#domain-cross]
== Domain Crossing

_Domains_ in Capstone-RISC-V are individual software compartments that
are protected by a safe context switching mechanism, i.e., domain crossing.
The mechanism is provided by the CALL and RETURN instructions.

.CALL instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100000' }
]}
....

.RETURN instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100001' }
]}
....

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `0` (normal world).
* `rs1` does not contain a capability.
* The `valid` field of the capability in `rs1` is `0` (invalid).
* The `type` field of the capability in `rs1` is not `4` (sealed).

For RETURN, an exception is raised also when any of the following conditions are met:

* `rs2` does not contain an integer

*If no exception is raised:*

For CALL:

. Load the content at the memory location `[base, base + CLEN)`,
where `base` is the `base` field of the capability in `rs1`, to the program counter (`pc`).
. For `i = 1, 2, ..., count`, load the content at the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, where `count` is the `count` field of the
capability in `rs1`, to `x[i]` (the `i`-th general-purpose register).
. Store the old `pc` value to the memory location `[base, base + CLEN)`, and the old
`sp` value to the memory location `[base + CLEN, base + 2 * CLEN)`.
. Set the `type` field of the capability in `rs1` to `5` (sealed-return), and write the
capability to the register `cra`.

For RETURN when the content of `rs1` is `0`:

. Load the content at the memory location `[base, base + CLEN)`,
where `base` is the `base` field of the capability in `rs1`, to the program counter (`pc`).
. For `i = 1, 2, ..., 31`, load the content at the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, to `x[i]` (the `i`-th general-purpose register).
. Write the old `pc` value with the `cursor` field replaced with the content of `rs2` to
the memory location `[base, base + CLEN)`.
. For `i = 1, 2, ..., count`, store the content of `x[i]` (the `i`-th general-purpose register)
to the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, where `count` is the `count` field of the capability in `rs1`.
. Set the `type` field of the capability in `rs1` to `4` (sealed), and write the
capability to the exception handler register `ceh`.

For RETURN when the content of `rs1` is not `0`:

. Load the content at the memory location `[base, base + CLEN)`,
where `base` is the `base` field of the capability in `rs1`, to the program counter (`pc`).
. Load the content at the memory location `[base + CLEN, base + 2 * CLEN)`,
where `base` is the `base` field of the capability in `rs1`, to the stack pointer (`sp`).
. Write the old `pc` value with the `cursor` field replaced with the content of `rs2` to
the memory location `[base, base + CLEN)`.
. For `i = 1, 2, ..., count`, store the content of `x[i]` (the `i`-th general-purpose register)
to the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, where `count` is the `count` field of the capability in `rs1`.
. Set the `type` field of the capability in `rs1` to `4` (sealed), and write the
capability to the register `x[reg]` where `reg` is the `reg` field of the capability in `rs1`.

[#world-switch]
== World Switching

TransCapstone-RISC-V is an extended version of Capstone-RISC-V which adds
a pair of extra instructions CAPENTER and CAPEXIT to support switching
between the secure world and the normal world. 
The CAPENTER instruction causes an entry into the secure world from the
normal world, and the CAPEXIT instruction causes an exit from the secure
world into the normal world.

.CAPENTER instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0100100' }
]}
....

.CAPEXIT instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: '0b0100101' }
]}
....

The CAPENTER instruction can only be used in the normal world, whereas
the CAPEXIT instruction can only be used in the secure world.
In addition, the CAPEXIT instruction can only be used when an exit capability
is provided.
Attempting to use those instructions in the wrong world or without the
required capability will cause an exception.
The behaviours of those 
instructions roughly correspond to the CALL and RETURN instructions
respectively.

=== CAPENTER

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `1` (secure world).
* `rs1` does not contain a capability.
* The `valid` field of the capability in `rs1` is `0` (invalid).
* The `type` field of the capability in `rs1` is not `4` (sealed).

*If no exception is raised:*

. Load the content at the memory location `[base, base + CLEN)`,
where `base` is the `base` field of the capability in `rs1`, to the program counter (`pc`).
. For `i = 1, 2, ..., count`, load the content at the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, where `count` is the `count` field of the
capability in `rs1`, to `x[i]` (the `i`-th general-purpose register).
. Store the old `pc` value to `normal_pc`, and the old
`sp` value to `normal_sp`.
. Set the `type` field of the capability in `rs1` to `5` (sealed-return), and write the
capability to the register `switch_cap`.
. Write `rs1` to the register `switch_reg`.
. Create a capability of `type = 6` (exit) in `cra`.

=== CAPEXIT

*An exception is raised when any of the following conditions are met:*

* `cwrld` is `0` (normal world).
* `rs1` does not contain a capability.
* The `valid` field of the capability in `rs1` is `0` (invalid).
* The `type` field of the capability in `rs1` is not `6` (exit).
* `rs2` does not contain an integer.
* The `valid` field of the capability in `switch_cap` is `0` (invalid).

*If no exception is raised:*

. Write the content of `normal_pc` and `normal_sp` to `pc` and `sp` respectively.
. Write the old `pc` content with the `cursor` field replaced with the content of `rs2` to
the memory location `[base, base + CLEN)`, where `base` is the `base` field of the capability in `switch_cap`.
. For `i = 1, 2, ..., count`, store the content of `x[i]` (the `i`-th general-purpose register) to
the memory location
`[base + i * CLEN, base + (i + 1) * CLEN)`, where `count` is the `count` field of the capability in `switch_cap`.
. Set the `type` field of `switch_cap` to `4` (sealed) and write it to `x[switch_reg]`.
