:reproducible:

= Control State Instructions

[#ccsr-man]
== Capability CSR (CCSR) Manipulation

The CCSRRW instruction is used to read and write specified link:#ccsrs-list[capability CSRs] (CCSRs).

.CCSRRW instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (Z)' }
]}
....

*An exception is raised when any of the following conditions are met:*

- Unexpected operand type (24)
* `x[rs1]` is not a capability.
- Illegal operand value (29)
* The immediate value `imm` does not correspond to the encoding of a valid capability CSR.

*If no exception is raised:*

. Read from capability CSR
** If the link:#ccsr-man-constr[read constraint] is satisfied, the content of the capability CSR specified by the immediate value `imm` is written to `x[rd]`.
If the current content of the capability CSR is neither a non-linear capability (i.e., `type != 1`) nor an exit capability (i.e., `type != 6`), it will be set to the content of `cnull`.
** Otherwise, `x[rd]` is set to the content of `cnull`.
. Write to capability CSR
** If the link:#ccsr-man-constr[write constraint] is satisfied, `x[rs1]` is written to the capability CSR specified by the immediate value `imm`.
If `x[rs1]` is neither a non-linear capability (i.e., `type != 1`) nor an exit capability (i.e., `type != 6`),
it will be set to the content of `cnull`.
** Otherwise, the original current of the capability CSR is preserved.
