:reproducible:

[appendix]
= Debugging Instructions (Non-Normative)

== Instruction Listing

.Debugging instructions
[%header%autowidth.stretch]
|===
|Mnemonic |Format |Func3  |Func7 | rs1 | rs2 | rd | imm[11:0] | World | Variant
|QUERY       |R |`000`    |`0000000` | I | - | - | - | * | *
|RCUPDATE    |R |`000`    |`0000001` | I | - | I | - | * | *
|ALLOC       |R |`000`    |`0000010` | I | - | I | - | * | *
|REV         |R |`000`    |`0000011` | I | - | - | - | * | *
|CAPCREATE   |R |`000`    |`0000100` | - | - | C | - | * | *
|CAPTYPE     |R |`000`    |`0000101` | I | - | C | - | * | *
|CAPNODE     |R |`000`    |`0000110` | I | - | C | - | * | *
|CAPPERM     |R |`000`    |`0000111` | I | - | C | - | * | *
|CAPBOUND    |R |`000`    |`0001000` | I | I | C | - | * | *
|CAPPRINT    |R |`000`    |`0001001` | I | - | - | - | * | *
|TAGSET      |R |`000`    |`0001010` | I | I | - | - | * | *
|TAGGET      |R |`000`    |`0001011` | I | - | I | - | * | *
|link:#debug-wrld[SETWORLD]    |R |`000`    |`0001100` | I | - | - | - | * | T
|link:#debug-wrld[ONPARTITION] |R |`000`    |`0001101` | I | - | - | - | * | T
|link:#debug-except[SETEH]       |R |`000`    |`0001110` | C | - | - | - | * | T
|link:#debug-except[ONNORMALEH]  |R |`000`    |`0001111` | I | - | - | - | * | T
|===

[#debug-wrld]
== World Switching

The instructions SETWORLD and ONPARTITION are related to world switching
in {isa_var_hybrid}. 

.SETWORLD instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001100' }
]}
....

.ONPARTITION instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001101' }
]}
....

The instructions load their operands from
the register `x[rs1]`, which expects
an integer.
SETWORLD directly sets the core to the specified
world (`0` for normal world and non-zero for secure world).
The program counter will also be made into a capability or an integer
correspondingly while retaining the `cursor` value.
ONPARTITION switches on (non-zero) or off (`0`) the world partitioning checks
in memory.

The instructions make it easy to set up the environment for testing
either {isa_var_pure} or {isa_var_hybrid}:

* {isa_var_pure}: secure world, world partitioning checks off
* {isa_var_hybrid}: normal world, world partitioning checks on

[#debug-except]
== Exception Handling

The instructions SETEH and ONNORMALEH affect the behaviours of interrupt and exception
handling.

.SETEH instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001110' }
]}
....

.ONNORMALEH instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: '*' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: '*' },
    {bits: 7, name: '0b0001111' }
]}
....

The SETEH instruction sets the secure-world
exception handler domain (i.e., `ceh`) to the specified capability
`x[rs1]`. 
The ONNORMALEH instruction checks `x[rs1]` and switches on (non-zero) or off (`0`) normal world handling of secure-world exceptions.
When this is on, an exception that occurs in the secure world will trap to the normal world
first before being handled by the secure-world exception handler (`ceh`), which is the
expected behaviour in {isa_var_hybrid}.
When it is off, the exception will be directly handled by the secure-world exception handler,
as is expected in {isa_var_pure}.

