:reproducible:

= Adjustments to Existing Instructions

For most of the existing instructions in {base_isa_name}, their behaviour is unmodified.
The `cursor` field (if `type != 4`) or `base` field (if `type = 4`) of the capability is used
if a register containing a capability is used as an operand.

The following instructions in {base_isa_name} are adjusted in {proj_name}:

****
* For memory access instructions, they are extended to use capabilities as addresses for memory access.
* For control flow instructions, they are slightly adjusted for the case where the program counter is a capability.
* Some instructions in {base_isa_name} become illegal instructions in _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world.
****

[#load-store]
== Memory Access Instructions

In {base_isa_name}, memory access instructions include load instructions
(i.e., `lb`, `lh`, `ld`, `lw`, `lbu`, `lhu`, `lwu`), and store instructions (i.e., `sb`, `sh`, `sw`, `sd`).
These instructions take an integer as a raw address, and load or store a value from/to this address.
In {proj_name}, these instructions are extended to take a capability as an address.

=== _{isa_var_pure}_

==== Load Instructions

In _{isa_var_pure}_, {base_isa_name} load instructions are modified to load integers of different
sizes using capabilities.

.*Note: `size` of load instructions*
[%collapsible]
====
****
The `size` used in this sections is the size (in bytes) of the integer being loaded.

[%header,%autowidth.stretch]
|===
|Mnemonic | `size`
|`lb` | `1`
|`lbu` | `1`
|`lh` | `2`
|`lhu` | `2`
|`lw` | `4`
|`lwu` | `4`
|`ld` | `8`
|===
****
====

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear), `1` (non-linear), `5` (sealed-return), or `6` (exit).
- `x[rs1].type` is `5` (sealed-return) and `x[rs1].async` is not `0` (synchronous).
* `Insufficient capability permissions (27)`
- `x[rs1].type` is `0` (linear) or 1 (non-linear) and `4 \<=p x[rs1].perms` does not hold.
* `Capability out of bound (28)`
- `x[rs1].type` is `0` (linear) or `1` (non-linear), and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base, x[rs1].end - size]`.
- `x[rs1].type` is `5` (sealed-return) or `6` (exit), and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base + 3 * CLENBYTES, x[rs1].base + 33 * CLENBYTES - size]`.
* `Load address misaligned (4)`
- `x[rs1].cursor + imm` is not aligned to `size` bytes.
****

.lb instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

.lh instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

.lw instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b010' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

.ld instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b011' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*If no exception is raised:*

====
* Load the content at the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + size)`
as a signed integer to `x[rd]`.
====

.lbu instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

.lhu instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b101' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

.lwu instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0000011'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b110' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*If no exception is raised:*

====
* Load the content at the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + size)`
as an unsigned integer to `x[rd]`.
====

==== Store Instructions

.*Note: `size` of store instructions*
[%collapsible]
====
****
The `size` used in this sections is the size (in bytes) of the integer being stored.

[%header,%autowidth.stretch]
|===
|Mnemonic | `size`
|`sb` | `1`
|`sh` | `2`
|`sw` | `4`
|`sd` | `8`
|===
****
====

.sb instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0100011'},
    {bits: 5, name: 'imm[4:0] (S)' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[11:5] (S)' }
]}
....

.sh instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0100011'},
    {bits: 5, name: 'imm[4:0] (S)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[11:5] (S)' }
]}
....

.sw instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0100011'},
    {bits: 5, name: 'imm[4:0] (S)' },
    {bits: 3, name: '0b010' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[11:5] (S)' }
]}
....

.sd instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0100011'},
    {bits: 5, name: 'imm[4:0]' },
    {bits: 3, name: '0b011' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[11:5]' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not an integer.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear), `1` (non-linear), `3` (uninitialised), `5` (sealed-return), or `6` (exit).
- `x[rs1].type` is `5` (sealed-return) and `x[rs1].async` is not `0` (synchronous).
* `Insufficient capability permissions (27)`
- `x[rs1].type` is `0` or `1`, and `2 \<=p x[rs1].perms` does not hold.
* `Illegal operand value (29)`
- `x[rs1].type` is `3` (uninitialised) and `imm` is not `0`.
* `Capability out of bound (28)`
- `x[rs1].type` is `0`, `1`, or `3`, and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base, x[rs1].end - size]`.
- `x[rs1].type` is `5` or `6`, and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base + 3 * CLENBYTES, x[rs1].base + 33 * CLENBYTES - size]`.
* `Store/AMO address misaligned (6)`
- `x[rs1].cursor + imm` is not aligned to `size` bytes.
****

*If no exception is raised:*

====
. Store `x[rs2]` to the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + size)` as an integer.
. The content in the `CLENBYTES`-byte aligned memory location `[cbase, cend)`, which aliases with
the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + size)`, is set to integer type,
where `cbase = (x[rs1].cursor + imm) & ~(CLENBYTES - 1)` and `cend = cbase + CLENBYTES`.
. If `x[rs1].type` is `3` (uninitialised), set `x[rs1].cursor` to `x[rs1].cursor + size`.
====

=== _{isa_var_hybrid}_

In _{isa_var_hybrid}_ secure world (i.e., `cwrld` is `1`),
{base_isa_name} memory access instructions behave the same as in _{isa_var_pure}_.

However, in _{isa_var_hybrid}_ normal world (i.e., `cwrld` is `0`),
these instructions behave differently in different _encoding modes_.

****
* When `cwrld` is `0` (normal world) and `emode` is `1` (capability encoding mode), these instructions
behave the same as in _{isa_var_pure}_.
* When `cwrld` is `0` (normal world) and `emode` is `0` (integer encoding mode), these instructions
behave the same as in {base_isa_name} except that the following adjustments are made to these instructions:
- An `Load access fault (5)` (for load) or `Store/AMO access fault(7)` (for store) exception is raised
if the address to be accessed (i.e., `x[rs1] + imm`) is within the range `(SBASE - size, SEND)`.
- For store instructions (i.e., `sb`, `sh`, `sw`, `sd`), the content in the `CLENBYTES`-byte aligned memory location
`[cbase, cend)`, which aliases with memory location `[x[rs1] + imm, x[rs1] + imm + size)`,
is set to integer type, where `cbase = (x[rs1] + imm) & ~(CLENBYTES - 1)` and `cend = cbase + CLENBYTES`.
****

.*Note: undefined behaviour*
[%collapsible]
====
****
The following load results are _undefined_:

* Load an integer from a memory location when the last capability store to its `CLENBYTES`-byte aligned memory location is
more recent than the last integer store to the memory location itself.
****
====

== Control Flow Instructions

In {base_isa_name}, conditional branch instructions (i.e., `beq`, `bne`, `blt`, `bge`, `bltu`, and `bgeu`),
and unconditional jump instructions (i.e., `jal` and `jalr`) are used to control the flow of execution.
In {proj_name}, these instructions are adjusted to support the situation where the program counter is a capability.

=== Branch Instructions

.beq instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

.bne instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b001' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

.blt instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

.bge instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b101' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

.bltu instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b110' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

.bgeu instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100011'},
    {bits: 5, name: 'imm[4:1|11] (S)' },
    {bits: 3, name: '0b111' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (I)' },
    {bits: 7, name: 'imm[12|10:5] (S)' }
]}
....

*The following adjustments are made to these instructions:*

****
_{isa_var_pure}_

* `pc.cursor`, instead of `pc`, is changed by the instruction.

_{isa_var_hybrid}_

* When `cwrld` is `1` (secure world), `pc.cursor`, instead of `pc`, is changed by the instruction.
****

=== Jump Instructions

.jal instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1101111'},
    {bits: 5, name: 'rd (I)' },
    {bits: 20, name: 'imm[20|10:1|11|19:12] (S)' }
]}
....

.jalr instruction format
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1100111'},
    {bits: 5, name: 'rd (I)' },
    {bits: 3, name: '0b000' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*The following adjustments are made to these instructions:*

****
_{isa_var_pure}_

* `pc.cursor + 4`, instead of `pc + 4`, is written to `x[rd]`.
* `pc.cursor`, instead of `pc`, is changed by the instruction.

_{isa_var_hybrid}_

* When `cwrld` is `1` (secure world), `pc.cursor + 4`, instead of `pc + 4`, is written to `x[rd]`.
* When `cwrld` is `1` (secure world), `pc.cursor`, instead of `pc`, is changed by the instruction.
****

== Illegal Instructions

Some instructions in {base_isa_name} now raise `illegal instruction (2)` exceptions
when executed in _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world, under all or some circumstances.

These instructions are:

****
* All instructions defined in the https://riscv.org/wp-content/uploads/2017/05/riscv-privileged-v1.10.pdf[privileged ISA] of {base_isa_name}.
* All instructions defined in the https://riscv.org/wp-content/uploads/2019/12/riscv-spec-20191213.pdf[{base_isa_csr_ext} extension],
namely instructions that directly access CSRs, when the CSR specified is not
<<additional-regs,one defined in {isa_name}>>,
or when the <<csr-man-constr,read/write constraints>> are not satisfied.
* `ecall`.
* `ebreak`.
****
