:reproducible:

= Memory Access Instructions

{isa_name} provides instructions to load and store capabilities from/to memory regions.

[#load-cap]
== Load Capabilities

github_ref:LDC[Sail definition]

The LDC instruction loads a capability from the memory.

=== Secure world or normal world capability encoding mode

The LDC instruction loads a capability from the memory using a capability,
when `cwrld` is `1` (secure world),
or when `cwrld` is `0` (normal world) but `emode` is `1` (capability encoding mode).

.LDC instruction format in secure world or normal world capability encoding mode
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b011' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear), `1` (non-linear), `5` (sealed-return), or `6` (exit).
- `x[rs1].type` is `5` (sealed-return) and `x[rs1].async` is not `0` (synchronous).
* `Insufficient capability permissions (27)`
- `x[rs1].type` is `0` (linear) or `1` (non-linear) and `4 \<=p x[rs1].perms` does not hold.
* `Capability out of bound (28)`
- `x[rs1].type` is `0` (linear) or `1` (non-linear), and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base, x[rs1].end - CLENBYTES]`.
- `x[rs1].type` is `5` (sealed-return) or `6` (exit), and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base + 3 * CLENBYTES, x[rs1].base + 33 * CLENBYTES - CLENBYTES]`.
* `Load address misaligned (4)`
- `x[rs1].cursor + imm` is not aligned to `CLENBYTES` bytes.
* `Load access fault (5)`
- The data contained in the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + CLENBYTES)` is not a capability.
* `Insufficient capability permissions (27)`
- The capability being loaded is not a non-linear capability (i.e., `type != 1`),
`x[rs1].type` is `0` (linear) or `1` (non-linear), and `2 \<=p x[rs1].perms` does not hold.
****

*If no exception is raised:*

====
. Set `cap` to `x[rs1]`.
. Load the capability at the memory location `cap.cursor + imm, cap.cursor + imm + CLENBYTES)` into `x[rd]`.
. If `x[rd].type` is not `1` (non-linear),
write `cnull` to the memory location `[cap.cursor + imm, cap.cursor + imm + CLENBYTES)`.
====

=== Normal world integer encoding mode

When `cwrld` is `0` (normal world) and `emode` is `0` (integer encoding mode),
the LDC instruction loads a capability from the normal memory using raw addresses.
The raw addresses are interpreted as physical addresses or virtual addresses
depending on the whether virtual memory is enabled.

.LDC instruction format in normal world integer encoding mode
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'rd (C)' },
    {bits: 3, name: '0b011' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 12, name: 'imm[11:0] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not an integer.
* `Load address misaligned (4)`
- `x[rs1] + imm` is not aligned to `CLENBYTES` bytes.
* `Load access fault (5)`
- `x[rs1] + imm` is in the range `[SBASE, SEND)`.
- The data contained in the memory location `[x[rs1] + imm, x[rs1] + imm + CLENBYTES)` is not a capability.
****

*If no exception is raised:*

====
. Set `int` to `x[rs1]`.
. Load the capability at the memory location `[int + imm, int + imm + CLENBYTES)` into `x[rd]`.
. If `x[rd].type` is not `1` (non-linear),
write `cnull` to the memory location `[int + imm, int + imm + CLENBYTES)`.
====

[#store-cap]
== Store Capabilities

github_ref:STC[Sail definition]

The STC instruction stores a capability to the memory.

=== Secure world or normal world capability encoding mode

The STC instruction stores a capability to the memory using a capability,
when `cwrld` is `1` (secure world),
or when `cwrld` is `0` (normal world) but `emode` is `1` (capability encoding mode).

.STC instruction format in secure world or normal world capability encoding mode
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'imm[4:0] (S)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (C)' },
    {bits: 5, name: 'rs2 (C)' },
    {bits: 7, name: 'imm[11:5] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not a capability.
- `x[rs2]` is not a capability.
* `Invalid capability (25)`
- `x[rs1].valid` is `0` (invalid).
* `Unexpected capability type (26)`
- `x[rs1].type` is not `0` (linear), `1` (non-linear), `3` (uninitialised), `5` (sealed-return), or `6` (exit).
- `x[rs1].type` is `5` (sealed-return) and `x[rs1].async` is not `0` (synchronous).
* `Insufficient capability permissions (27)`
- `x[rs1].type` is `0` or `1`, and `2 \<=p x[rs1].perms` does not hold.
* `Illegal operand value (29)`
- `x[rs1].type` is `3` (uninitialised) and `imm` is not `0`.
* `Capability out of bound (28)`
- `x[rs1].type` is `0`, `1`, or `3`, and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base, x[rs1].end - CLENBYTES]`.
- `x[rs1].type` is `5` or `6`, and `x[rs1].cursor + imm` is
not in the range `[x[rs1].base + 3 * CLENBYTES, x[rs1].base + 33 * CLENBYTES - CLENBYTES]`.
* `Store/AMO address misaligned (6)`
- `x[rs1].cursor + imm` is not aligned to `CLENBYTES` bytes.
****

*If no exception is raised:*

====
. Store `x[rs2]` to the memory location `[x[rs1].cursor + imm, x[rs1].cursor + imm + CLENBYTES)`.
. If `x[rs1].type` is `3` (uninitialised), set `x[rs1].cursor` to `x[rs1].cursor + CLENBYTES`.
. If `x[rs2].type` is not `1` (non-linear), write `cnull` to `x[rs2]`.
====

=== Normal world integer encoding mode

When `cwrld` is `0` (normal world) and `emode` is `0` (integer encoding mode),
the STC instruction stores a capability to the normal memory using raw addresses.
The raw addresses are interpreted as physical addresses or virtual addresses
depending on the whether virtual memory is enabled.

.STC instruction format in normal world integer encoding mode
[wavedrom,,svg]
....
{reg: [
    {bits: 7, name: '0b1011011'},
    {bits: 5, name: 'imm[4:0] (S)' },
    {bits: 3, name: '0b100' },
    {bits: 5, name: 'rs1 (I)' },
    {bits: 5, name: 'rs2 (C)' },
    {bits: 7, name: 'imm[11:5] (S)' }
]}
....

*An exception is raised when any of the following conditions is met:*

****
* `Unexpected operand type (24)`
- `x[rs1]` is not an integer.
- `x[rs2]` is not a capability.
* `Store/AMO address misaligned (6)`
- `x[rs1] + imm` is not aligned to `CLENBYTES` bytes.
* `Store/AMO access fault (7)`
- `x[rs1] + imm` is in the range `[SBASE, SEND)`.
****

*If no exception is raised:*

====
. Store `x[rs2]` to the memory location `[x[rs1] + imm, x[rs1] + imm + CLENBYTES)`.
. If `x[rs2].type` is not `1` (non-linear), write `cnull` to `x[rs2]`.
====
