:reproducible:

= Programming Model

The {isa_name} ISA has extended part of the machine state,
including both some registers and the memory, to
enable the storage and handling of capabilities.

== Capabilities

=== Width

The width of a capability is 128 bits. We represent this as
`CLEN = 128` and `CLENBYTES = 16`. Note that this does not
affect the width of a raw address, which is `XLEN = 64` bits,
or equivalently, `XLENBYTES = 8` bytes, same as
in {base_isa_name}.

=== Fields

Each capability has the following architecturally-visible fields:

.Fields in a capability
[%header,%autowidth.stretch]
|===
|Name |Range |Description
|`valid` | `0..1` | Whether the capability is valid: `0` = invalid, `1` = valid
|`type` | `0..6` | The type of the capability:
`0` = linear, `1` = non-linear, `2` = revocation,
`3` = uninitialised, `4` = sealed, `5` = sealed-return, `6` = exit
|`cursor` | `0..2^XLEN-1` |  Not applicable when `type = 4` (sealed).
The memory address the capability points to (to be used for the next memory access)
|`base` | `0..2^XLEN-1` | The base memory address of the memory region associated with the capability
|`end` | `0..2^XLEN-1` | Not applicable when `type = 4` (sealed), `type = 5` (sealed-return), or
`type = 6` (exit).
The end memory address of the memory region associated with the capability
|`perms` | `0..7` | Not applicable when `type = 4` (sealed), `type = 5` (sealed-return), or
`type = 6` (exit).
One-hot encoded permissions associated with the capability:
`0` = no access, `1` = execute-only, `2` = write-only, `3` = write-execute,
`4` = read-only, `5` = read-execute, `6` = read-write, `7` = read-write-execute
|`async` | `0..2` | Only applicable when `type = 4` (sealed) or `type = 5` (sealed-return).
How the capability is sealed: `0` = synchronously, `1` = upon exception, `2` = upon interrupt
|`reg` | `0..31` | Only applicable when `type = 5` (sealed-return).
The index of the general-purpose register to restore the capability to
|===

The range of the `perms` field has a partial order `\<=p` defined as follows:
....
<=p = {
    (0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7),
    (1, 1), (1, 3), (1, 5), (1, 7),
    (2, 2), (2, 3), (2, 6), (2, 7),
    (3, 3), (3, 7),
    (4, 4), (4, 5), (4, 6), (4, 7),
    (5, 5), (5, 7),
    (6, 6), (6, 7),
    (7, 7)
}
....

[#alias-definition]
We say a capability `c` _aliases_ with a capability `d` if and only if the intersection
between `[c.base, c.end)` and `[d.base, d.end)` is non-empty.

[#smaller-t-definition]
For two revocation capabilities `c` and `d` (i.e., `c.type = d.type = 2`),
we say `c <t d` if and only if

* `c` aliases with `d`
* The creation of `c` was earlier than the creation of `d`

In addition to the above fields, an implementation also needs to maintain
sufficient metadata to test the `<t` relation.
It will be clear that for any pair of aliasing revocation capabilities,
the order of their creations is well-defined.

.*Note: the implementation of `valid` field*
[%collapsible]
====
****
The `valid` field is involved in <<revocation,revocation>>,
where it might be changed due to a <<rev-operation,revocation operation>>
on a different capability.
A performant implementation, therefore, may prefer not to maintain
the `valid` field inline with the other fields.
****
====

.*Note: addition/compression to capability fields*
[%collapsible]
====
****
Implementations are free to maintain additional fields to
capabilities, or compress the representation of the above
fields, as long as each capability fits in `CLEN` bits.

It is not required to be able to represent capabilities with
all combinations of field values in a compressed representation,
as long as the following conditions are satisfied:

. For load and store instructions that move a capability between
a register and memory, the value of the capability is preserved.
. The resulting capability values of any operation are not more
powerful than when the same operation is performed on a {isa_name}
implementation without compression.
- More specifically, if an execution trace is valid
(i.e., without exceptions) on the compressed implementation, 
then it must also be valid on the uncompressed implementation.
// FIXME: double-check this claim
For example, a trivial yet useless compression would be to store
nothing and always return a capability with `valid = 0`.
****
====

For different types of capabilities, a specific subset of the fields is used.
The table below summarises the fields used for each type of capabilities.

.Fields used for each type of capabilities
[%header,%autowidth.stretch]
|===
|Type |`type` |`valid` |`cursor` |`base` |`end` |`perms` |`async` |`reg`
|Linear |`0` |Yes |Yes |Yes |Yes |Yes |- |-
|Non-linear |`1` |Yes |Yes |Yes |Yes |Yes |- |-
|Revocation |`2` |Yes |Yes |Yes |Yes |Yes |- |-
|Uninitialised |`3` |Yes |Yes |Yes |Yes |Yes |- |-
|Sealed |`4` |Yes |- |Yes |- |- |Yes |-
|Sealed-return |`5` |Yes |Yes |Yes |- |- |Yes |Yes
|Exit |`6` |Yes |Yes |Yes |- |- |- |-
|===

When the `async` field of a sealed-return capability is `0` (synchronous),
or when the `type` field of the capability is `6` (exit),
some memory accesses are granted by this capability.
The following table shows the memory accesses granted in such scenarios,
where `size` is the size of the memory access in bytes.

.Memory accesses granted by sealed-return and exit capabilities
[%header%autowidth.stretch]
|===
| Capability type | `async` | Read | Write | Execute
| Sealed-return | `0` | `cursor in [base + 3 * CLENBYTES, base + 33 * CLENBYTES - size]` | `cursor in [base + 3 * CLENBYTES, base + 33 * CLENBYTES - size]` | No
| Exit | - | `cursor in [base + 3 * CLENBYTES, base + 33 * CLENBYTES - size]` | `cursor in [base + 3 * CLENBYTES, base + 33 * CLENBYTES - size]` | No
|===

In other scenarios and for other capability types without the `perms` field, no read/write/execute
memory accesses are granted by the capability.

****
The following figure shows the overview of different types of capabilities in _{isa_var_pure}_,
and the operations that change the type of a capability.

.Overview of different types of capabilities in _{isa_var_pure}_
image::pure-types.svg[pure-types]
****

****
The following figure shows the overview of different types of capabilities in _{isa_var_hybrid}_,
and the operations that change the type of a capability.

.Overview of different types of capabilities in _{isa_var_hybrid}_
image::trans-types.svg[trans-types]
****

== Extension to General-Purpose Registers

The {isa_name} ISA extends each of the 32 general-purpose
registers, so it contains either a capability or a raw `XLEN`-bit
integer.
The type of data contained in a register is maintained and confusion
of the type is not allowed, except for `x0`/`c0` as discussed below.
In assembly code, the type of data expected in a register operand
is indicated by the alias used for the register, as summarised
in the following table.

[%header%autowidth.stretch]
|===
| Index | `XLEN`-bit integer | Capability
| 0 | `x0`/`zero` | `c0`/`cnull` 
| 1 | `x1`/`ra` | `c1`/`cra`
| 2 | `x2`/`sp` | `c2`/`csp`
| 3 | `x3`/`gp` | `c3`/`cgp`
| 4 | `x4`/`tp` | `c4`/`ctp`
| 5 | `x5`/`t0` | `c5`/`ct0`
| 6 | `x6`/`t1` | `c6`/`ct1`
| 7 | `x7`/`t2` | `c7`/`ct2`
| 8 | `x8`/`s0`/`fp` | `c8`/`cs0`/`cfp`
| 9 | `x9`/`s1` | `c9`/`cs1`
| 10 | `x10`/`a0` | `c10`/`ca0`
| 11 | `x11`/`a1` | `c11`/`ca1`
| 12 | `x12`/`a2` | `c12`/`ca2`
| 13 | `x13`/`a3` | `c13`/`ca3`
| 14 | `x14`/`a4` | `c14`/`ca4`
| 15 | `x15`/`a5` | `c15`/`ca5`
| 16 | `x16`/`a6` | `c16`/`ca6`
| 17 | `x17`/`a7` | `c17`/`ca7`
| 18 | `x18`/`s2` | `c18`/`cs2`
| 19 | `x19`/`s3` | `c19`/`cs3`
| 20 | `x20`/`s4` | `c20`/`cs4`
| 21 | `x21`/`s5` | `c21`/`cs5`
| 22 | `x22`/`s6` | `c22`/`cs6`
| 23 | `x23`/`s7` | `c23`/`cs7`
| 24 | `x24`/`s8` | `c24`/`cs8`
| 25 | `x25`/`s9` | `c25`/`cs9`
| 26 | `x26`/`s10` | `c26`/`cs10`
| 27 | `x27`/`s11` | `c27`/`cs11`
| 28 | `x28`/`t3` | `c28`/`ct3`
| 29 | `x29`/`t4` | `c29`/`ct4`
| 30 | `x30`/`t5` | `c30`/`ct5`
| 31 | `x31`/`t6` | `c31`/`ct6`
|===

`x0`/`c0` is a read-only register that can be used both as an
integer and as a capability, depending on the context. When used
as an integer, it has the value `0`.
When used as a capability, it has the value
`{ valid = 0, type = 0, cursor = 0, base = 0, end = 0, perms = 0 }`.
Any attempt to write to `x0`/`c0` will be silently ignored (no
exceptions are raised).

In this document,
for `i = 0, 1, ..., 31`, we use `x[i]` to refer to the general-purpose
register with index `i`.

== Extension to Other Registers

=== Program Counter

The following changes are made to the program counter (`pc`):

* _{isa_var_pure}_: the program counter (`pc`) is changed to contain a capability only.
* _{isa_var_hybrid}_: similar to the general-purpose registers,
the program counter (`pc`) is extended to contain a capability or an integer.

.*Note: what is `cwrld`*
[%collapsible]
====
****
`cwrld` is a special register added in _{isa_var_hybrid}_ that indicates the world currently in execution.
Please see <<additional-regs,Added Registers>> for details.
****
====

*During the instruction fetch stage, an exception is raised when any of the following conditions is met:*

****
_{isa_var_pure}_

* `Instruction access fault (1)`
- `pc.valid` is `0` (invalid).
- `pc.type` is neither `0` (linear) nor `1` (non-linear).
- `pc.perms` is not executable (i.e., `1 \<=p pc.perms` does not hold).
- `pc.cursor` is not in the range `[pc.base, pc.end - 4]`.
* `Instruction address misaligned (0)`
- `pc.cursor` is not aligned to `4`.

_{isa_var_hybrid}_

* `cwrld` is `1` (secure world) and any of the conditions for _{isa_var_pure}_ is met.
* `cwrld` is `0` (normal world) and any of the conditions for {base_isa_name} is met.
* `Instruction access fault (1)`
- `cwrld` is `1` (secure world) and `pc` does not contain a capability.
- `cwrld` is `0` (normal world) and `pc` does not contain an integer.
****

*If no exception is raised:*

====
_{isa_var_pure}_ or _{isa_var_hybrid}_ secure world (i.e., `cwrld = 1`)

. The instruction pointed to by `pc.cursor` is fetched and executed.
. Set `pc.cursor` to `pc.cursor + 4` at the end of the instruction.

_{isa_var_hybrid}_ normal world (i.e., `cwrld = 0`)

. The instruction pointed to by `pc` is fetched and executed.
. Set `pc` to `pc + 4` at the end of the instruction.
====

[#additional-regs]
== Added Registers

The {isa_name} ISA adds the following registers.

.Additional Registers in {isa_name} ISA
[#additional-regs]
[#add-reg-list, cols="1,3a", options="header"]
|===
|{proj_name} Variant   | Additional Registers
|_{isa_var_pure}_|
[cols="1,1,1,4", options="header"]
!===
! Mnemonic ! CCSR encoding ! CSR encoding ! Description
! `ceh`  ! `0x000` ! - ! The sealed capability or PC entry for the exception handler
! `cih`  ! `0x001` ! - ! The sealed capability for the interrupt handler
! `cinit` ! `0x002` ! - ! The initial capability covering the entire address space of the memory
! `epc` ! `0x003` ! - ! The exception program counter register
! `cis` ! - ! `0x800` ! The interrupt status register
! `tval` ! - ! `0x801` ! The exception data (trap value) register
! `cause` ! - ! `0x802` ! The exception cause register
!===

|_{isa_var_hybrid}_|
[cols="1,1,1,4", options="header"]
!===
! Mnemonic ! CCSR encoding ! CSR encoding ! Description
! `ceh`  ! `0x000` ! - ! The sealed capability or PC entry for the exception handler
! `cinit` ! `0x002` ! - ! The initial capability covering the entire address space of the secure memory
! `epc` ! `0x003` ! - ! The exception program counter register
! `cwrld`! - ! - ! The world currently in execution. `0` = normal world, `1` = secure world
! `normal_pc`!-!- !The program counter for the normal world before the secure world is entered
! `normal_sp`!-!-!The stack pointer for the normal world before the secure world is entered
! `switch_reg`!-!-! The index of the general-purpose register used when switching worlds
! `switch_cap`! `0x004` !-! The capability used to store contexts when switching worlds asynchronously
! `exit_reg`!-!-! The index of the general-purpose register for receiving the exit code when exiting the secure world 
! `tval` ! - ! `0x801` ! The exception data (trap value) register
! `cause` ! - ! `0x802` ! The exception cause register
! `emode` ! - ! `0x804` ! The encoding mode of the machine. `0` = integer encoding mode, `1` = capability encoding mode
!===
|===

Some of the registers only allow capability values and have special semantics
related to the system-wide machine state. They are referred to as
_capability control and status registers_ (CCSRs). Under their respective constraints,
CCSRs can be manipulated using _<<ctrl-status,control and status instructions>>_.

The manipulation constraints for each CCSR are indicated below.

.Manipulation Constraints for CCSRs
[#ccsr-man-constr]
[%header%autowidth.stretch]
|===
|Mnemonic | Read | Write
|`ceh` | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world
|`cih` | - | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world; the original content must not be a capability
|`cinit` | _{isa_var_pure}_ or _{isa_var_hybrid}_ normal world; one-time only | -
|`epc` | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world
|`switch_cap` | _{isa_var_hybrid}_ normal world | _{isa_var_hybrid}_ normal world
|===

The manipulation constraints for each additional CSR are indicated below.

.Manipulation Constraints for Additional CSRs
[#csr-man-constr]
[%header%autowidth.stretch]
|===
|Mnemonic | Read | Write
|`cis`| _{isa_var_pure}_; `cih` must not be a capability | _{isa_var_pure}_; `cih` must not be a capability
|`tval`| _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world
|`cause`| _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world | _{isa_var_pure}_ or _{isa_var_hybrid}_ secure world
|`emode`| _{isa_var_hybrid}_ normal world | _{isa_var_hybrid}_ normal world
|===

.*Note: `ceh` and `cih`*
[%collapsible]
====
****
`ceh` and `cih` should be handled differently.

`ceh` is about the functionality of a domain only.
A domain should be allowed to set `ceh` for itself.
That also means it needs to be switched when switching domains.

`cih` is about the functionality of the system,
which should normally only be set once.
To prevent any domain from setting `cih`, we require the original content of
`cih` to be invalid for an attempt to change it to succeed.
****
====

.*Note: `cinit`*
[%collapsible]
====
****
`cinit` is a CCSR that is used to
bootstrap capabilities after a <<reset,system reset>>.
<<ctrl-status,control and status instructions>> can be used to read the initial
capability in `cinit` and write it to a general-purpose register.
This operation can only be performed once after each reset.
Any attempt to write `cinit` will be silently ignored,
and any attempt to read it after the first time will return the content of `cnull`.
****
====

[#mem-extension]
== Extension to Memory

The memory is addressed using an `XLEN`-bit integer at byte-level
granularity.
In addition to raw integers, each `CLEN`-bit aligned address can
also store a capability.
The type of data contained in a memory location is maintained and
confusion of the type is not allowed.

In _{isa_var_pure}_, the memory can _only_ be accessed through capabilities.

[%header%autowidth.stretch]
|===
| Address Space | Access Method
| `[0, 2^XLEN)` | Capabilities
|===

In _{isa_var_hybrid}_, the physical memory is divided into two disjoint regions:
the _normal memory_ and the _secure memory_.
While the normal memory is only accessible through _Memory Management Unit_ (MMU),
the secure memory can only be accessed through capabilities.

The bounds of the secure memory `[SBASE, SEND)` are implementation-defined.
But both `SBASE` and `SEND` are required to be `CLENBYTES`-byte aligned.

[%header%autowidth.stretch]
|===
| Memory Region | Address Space | Access Method
| Normal memory | `[0, SBASE) U [SEND, 2^XLEN)` | MMU
| Secure memory | `[SBASE, SEND)` | Capabilities
|===

== Instruction Set

The {isa_name} instruction set is based on the {base_isa_name} instruction set.
The (uncompressed) instructions are fixed 32-bit wide, and laid out in memory
in little-endian order. In the encoding space of the {base_isa_name} instruction set,
{isa_name} instructions occupies the "`custom-2`" subset, i.e., the opcode
of all {isa_name} instructions is `0b1011011`.

{isa_name} instruction encodings follow three basic formats: R-type, I-type and S-type,
as described below
(more details are also provided in the https://github.com/riscv/riscv-isa-manual[_RISC-V ISA Manual_]).

.R-type instruction format
include::r-type-format.adoc[]

.I-type instruction format
include::i-type-format.adoc[]

.S-type instruction format
include::s-type-format.adoc[]

R-type instructions receive up to three register operands, and I-type/S-type instructions
receive up to two register operands and a 12-bit-wide immediate operand.

{isa_name} also adds a new instruction format, the CI-type format, which is used for
compressed immediate instructions.

.CI-type instruction format
include::ci-type-format.adoc[]

CI-type instructions receive up to two register operands and a 5-bit-wide immediate operand.

[#reset]
== System Reset

Upon reset, the system state must conform to the following
specifications.

_{isa_var_pure}_

****
* Each general-purpose register either contains an integer, or a capability with `valid = 0` (invalid).
* No addressable memory location can contain a capability.
* `ceh`, `cih`, and `epc` contain either integers or
capabilities with `valid = 0` (invalid).
* `cis = 0`.
* `cinit = { valid = 1, type = 0, cursor = INIT_DATA_BASE, base = INIT_DATA_BASE, end = INIT_DATA_END, perms = 7 }`,
and `pc = { valid = 1, type = 0, cursor = INIT_CODE_BASE, base = INIT_CODE_BASE, end = INIT_CODE_END, perms = 7 }`, where `INIT_DATA_BASE`, `INIT_DATA_END`, `INIT_CODE_BASE`, and `INIT_CODE_END` are implementation-defined, and `[INIT_CODE_BASE, INIT_CODE_END)` does not overlap with `[INIT_DATA_BASE, INIT_DATA_END)`.
****

_{isa_var_hybrid}_

****
* Each general-purpose register either contains an integer, or a capability with `valid = 0` (invalid).
* No addressable memory location can contain a capability.
* `ceh`, `epc` and `switch_cap` contain either an integer or
a capability with `valid = 0` (invalid).
* `cwrld = 0` (normal world).
* `cinit = { valid = 1, type = 0, cursor = SBASE, base = SBASE, end = SEND, perms = 7 }`.
* Specifications for {base_isa_name}.
****
