:reproducible:

= Programming Model

The Capstone-RISC-V ISA has extended the part of the machine state,
including both some registers and the memory, to
enable the storage and handling of capabilities.

== Capabilities

=== Width

The width of a capability is 128 bits. We represent this as
`CLEN = 128`. Note that this does not affect the width of a
raw address, which is `XLEN = 64` bits.

=== Fields

Each capability has the following architecturally-visible fields:

.Fields in a capability
[%header,%autowidth.stretch]
|===
|Name |Range |Description
|`type` | `0..5` | The type of the capability:
`0` = linear, `1` = non-linear, `2` = revocation,
`3` = uninitialised, `4` = sealed, `5` = sealed-return
|`cursor` | `0..2^XLEN-1` |  The memory address the capability points to (to be used for the next memory access)
|`base` | `0..2^XLEN-1` | The base memory address of the memory region associated with the capability
|`length` | `0..2^XLEN-1` | The length of the memory region associated with the capability
|`perms` | `0..4` | The permissions associated with the capability:
`0` = no access, `1` = read-only, `2` = read-execute,
`3` = read-write, `4` = read-write-execute
|===

.NOTE
****
Implementations are free to maintain additional fields to
capabilities or compress the representation of the above
fields, as long as each capability fits in `CLEN` bits.
****

== Extension to General-Purpose Registers

The Capstone-RISC-V ISA extends each of the 32 general-purpose
registers, so it contains either a capability or a raw `XLEN`-bit
integer.
The type of data contained in a register is maintained and confusion
of the type is not allowed.
In assembly code, the type of data expected in a register operand
is indicated by the alias used for the register, as summarised
in the following table.

[%header%authowidth.stretch]
|===
| `XLEN`-bit integer | Capability
| `x0`/`zero` | `c0`/`cnull` 
| `x1`/`ra` | `c1`/`cra`
| `x2`/`sp` | `c2`/`csp`
| `x3`/`gp` | `c3`/`cgp`
| `x4`/`tp` | `c4`/`ctp`
| `x5`/`t0` | `c5`/`ct0`
| `x6`/`t1` | `c6`/`ct1`
| `x7`/`t2` | `c7`/`ct2`
| `x8`/`s0`/`fp` | `c8`/`cs0`/`cfp`
| `x9`/`s1` | `c9`/`cs1`
| `x10`/`a0` | `c10`/`ca0`
| `x11`/`a1` | `c11`/`ca1`
| `x12`/`a2` | `c12`/`ca2`
| `x13`/`a3` | `c13`/`ca3`
| `x14`/`a4` | `c14`/`ca4`
| `x15`/`a5` | `c15`/`ca5`
| `x16`/`a6` | `c16`/`ca6`
| `x17`/`a7` | `c17`/`ca7`
| `x18`/`s2` | `c18`/`cs2`
| `x19`/`s3` | `c19`/`cs3`
| `x20`/`s4` | `c20`/`cs4`
| `x21`/`s5` | `c21`/`cs5`
| `x22`/`s6` | `c22`/`cs6`
| `x23`/`s7` | `c23`/`cs7`
| `x24`/`s8` | `c24`/`cs8`
| `x25`/`s9` | `c25`/`cs9`
| `x26`/`s10` | `c26`/`cs10`
| `x27`/`s11` | `c27`/`cs11`
| `x28`/`t3` | `c28`/`ct3`
| `x29`/`t4` | `c29`/`ct4`
| `x30`/`t5` | `c30`/`ct5`
| `x31`/`t6` | `c31`/`ct6`
|===

== Extension to Other Registers

The program counter (`pc`) register is extended to contain a
capability.

== Extension to Memory

The memory is addressed using an `XLEN`-bit integer at byte-level
granularity.
In addition to raw integers, each `CLEN`-bit aligned address can
also store a capability.
The type of data contained in a memory location is maintained and
confusion of the type is not allowed.

== Instruction Set

The Capstone-RISC-V instruction set is based on the RV64G instruction set.
The (uncompressed) instructions are fixed 32-bit wide, and laid out in memory
in little-endian order. In the encoding space of the RV64G instruction set,
Capstone-RISC-V instructions occupies the "custom-2" subset, i.e., the opcode
of all Capstone-RISC-V instructions is `0b1011011`.

Capstone-RISC-V instruction encodings follow two basic formats: R-type and I-type,
as described below (more details are also provided in the _RISC-V ISA Manual_).

.R-type instruction format
include::r-type-format.adoc[]

.I-type instruction format
include::i-type-format.adoc[]

R-type instructions receive up to three register operands, and I-type instructions
receive up to two register operands and a 12-bit-wide immediate operand.
